name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "cli/pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
        working-directory: cli
      - run: pnpm run build --if-present
        working-directory: cli
      - run: pnpm run test --if-present
        working-directory: cli
      - run: npm publish
        working-directory: cli
